Feat/field delete (#91)
* first implemtation of -f flag

* added testing

* added documentation

* update node.js to version 18 in workflow

* updated node.js version to 18 for master workflow

diff --git a/tests/tests b/tests/tests
--- a/tests/tests
+++ b/tests/tests
@@ -350,31 +350,62 @@ testCopyDocumentAndCollection(){
 }
 
 testDeleteRecursive(){
-      # adding new documents with nested sub-collections
-      id=$(../fuego add ${TEST_COLLECTION} "{\"base\": \"value\"}") || fail "Failed to add document"
-      subDocId1=$(../fuego add "${TEST_COLLECTION}/${id}/subCollection1" "{\"base\": \"sub value1\"}") || fail "Failed to add document"
-      subSubDocId1=$(../fuego add "${TEST_COLLECTION}/${id}/subCollection1/${subDocId1}/subSubCollection1" "{\"base\": \"subsub value1\"}")|| fail "Failed to add document"
+    # adding new documents with nested sub-collections
+    id=$(../fuego add ${TEST_COLLECTION} "{\"base\": \"value\"}") || fail "Failed to add document"
+    subDocId1=$(../fuego add "${TEST_COLLECTION}/${id}/subCollection1" "{\"base\": \"sub value1\"}") || fail "Failed to add document"
+    subSubDocId1=$(../fuego add "${TEST_COLLECTION}/${id}/subCollection1/${subDocId1}/subSubCollection1" "{\"base\": \"subsub value1\"}")|| fail "Failed to add document"
 
-      subDocId2=$(../fuego add "${TEST_COLLECTION}/${id}/subCollection2" "{\"base\": \"sub value2\"}") || fail "Failed to add document"
-      subSubDocId2=$(../fuego add "${TEST_COLLECTION}/${id}/subCollection2/${subDocId2}/subSubCollection2" "{\"base\": \"subsub value2\"}")|| fail "Failed to add document"
-      echo ${id} ${subDocId1} ${subSubDocId1} ${subDocId2} ${subSubDocId2}
+    subDocId2=$(../fuego add "${TEST_COLLECTION}/${id}/subCollection2" "{\"base\": \"sub value2\"}") || fail "Failed to add document"
+    subSubDocId2=$(../fuego add "${TEST_COLLECTION}/${id}/subCollection2/${subDocId2}/subSubCollection2" "{\"base\": \"subsub value2\"}")|| fail "Failed to add document"
+    echo ${id} ${subDocId1} ${subSubDocId1} ${subDocId2} ${subSubDocId2}
 
-      # delete one collection without recursive flag. To test deletion of missing documents.
-      ../fuego delete "${TEST_COLLECTION}/${id}/subCollection1" ${subDocId1}
-      assertFalse "Should not have read deleted value" "../fuego get ${TEST_COLLECTION}/${id}/subCollection1 ${subDocId1}"
+    # delete one collection without recursive flag. To test deletion of missing documents.
+    ../fuego delete "${TEST_COLLECTION}/${id}/subCollection1" ${subDocId1}
+    assertFalse "Should not have read deleted value" "../fuego get ${TEST_COLLECTION}/${id}/subCollection1 ${subDocId1}"
 
-      # check that sub-collection of deleted collection still exists
-      expectedValue=$(echo "{\"base\": \"subsub value1\"}" | jq .)
-      result=$(../fuego get "${TEST_COLLECTION}/${id}/subCollection1/${subDocId1}/subSubCollection1/${subSubDocId1}"  | jq .Data)
-      assertEquals "Should be able to read SubCollection" "${result}" "${expectedValue}"
+    # check that sub-collection of deleted collection still exists
+    expectedValue=$(echo "{\"base\": \"subsub value1\"}" | jq .)
+    result=$(../fuego get "${TEST_COLLECTION}/${id}/subCollection1/${subDocId1}/subSubCollection1/${subSubDocId1}"  | jq .Data)
+    assertEquals "Should be able to read SubCollection" "${result}" "${expectedValue}"
 
-      # call delete again, but with recursive flag.
-      ../fuego delete -r "${TEST_COLLECTION}" ${id}
+    # call delete again, but with recursive flag.
+    ../fuego delete -r "${TEST_COLLECTION}" ${id}
 
-      # check that all documents are deleted, also the missing documents.
-      assertFalse "Should not have read deleted value2" "../fuego get ${TEST_COLLECTION}/${id}/subCollection1/${subDocId1}/subSubCollection1 ${subSubDocId1}"
-      assertFalse "Should not have read deleted value3" "../fuego get ${TEST_COLLECTION}/${id}/subCollection2 ${subDocId2}"
-      assertFalse "Should not have read deleted value2" "../fuego get ${TEST_COLLECTION}/${id}/subCollection2/${subDocId2}/subSubCollection2 ${subSubDocId2}"
+    # check that all documents are deleted, also the missing documents.
+    assertFalse "Should not have read deleted value2" "../fuego get ${TEST_COLLECTION}/${id}/subCollection1/${subDocId1}/subSubCollection1 ${subSubDocId1}"
+    assertFalse "Should not have read deleted value3" "../fuego get ${TEST_COLLECTION}/${id}/subCollection2 ${subDocId2}"
+    assertFalse "Should not have read deleted value2" "../fuego get ${TEST_COLLECTION}/${id}/subCollection2/${subDocId2}/subSubCollection2 ${subSubDocId2}"
 }
+
+testFieldDelete(){
+    # adding new documents with sub-collections and two fields
+    id=$(../fuego add ${TEST_COLLECTION} "{\"base\": \"value\", \"base2\": \"value2\"}") || fail "Failed to add document"
+    subDocId1=$(../fuego add "${TEST_COLLECTION}/${id}/subCollection1" "{\"subbase\": \"sub value1\"}") || fail "Failed to add document"
+    subDocId2=$(../fuego add "${TEST_COLLECTION}/${id}/subCollection1/${subDocId1}/subCollection2" "{\"sub2base\": \"sub2 value1\"}") || fail "Failed to add document"
+    echo ${id} ${subDocId1} ${subDocId2}
+
+    # check preconditions for first level
+    result=$(../fuego get ${TEST_COLLECTION}/${id} | jq -c .Data)
+    expectedValue='{"base":"value","base2":"value2"}'
+    assertEquals "Preconditions Failed" "${result}" "${expectedValue}"
+
+    # delete field from first level
+    ../fuego delete -f "base2" ${TEST_COLLECTION}/${id}
+    result=$(../fuego get ${TEST_COLLECTION}/${id} | jq -c .Data)
+    expectedValue='{"base":"value"}'
+    assertEquals "Failed to delete from First level" "${result}" "${expectedValue}"
+
+    # check preconditions for second level
+    result=$(../fuego get ${TEST_COLLECTION}/${id}/subCollection1/${subDocId1} | jq -c .Data)
+    expectedValue='{"subbase":"sub value1"}'
+    assertEquals "Preconditions Failed" "${result}" "${expectedValue}"
+    
+    # delete field from second level
+    ../fuego delete -f "subbase" ${TEST_COLLECTION}/${id}/subCollection1/${subDocId1}
+    result=$(../fuego get ${TEST_COLLECTION}/${id}/subCollection1/${subDocId1} | jq -c .Data)
+    expectedValue='{}'
+    assertEquals "Failed to delete from First level" "${result}" "${expectedValue}"
+}
+
 # Load shUnit2.
 . ./shunit2
